# Generated by Django 3.0.7 on 2020-07-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
