# Generated by Django 3.0.7 on 2020-07-02 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0002_auto_20200702_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='urls_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
