# Generated by Django 3.0.7 on 2020-07-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webanalyzer', '0003_auto_20200702_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='urls_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webanalyzer.Link'),
        ),
    ]
